```{r indforestfunc, cache=cacheon}
indforest <- function(data, outtime, outvar, outval = 1) {
  out <- data.frame(matrix(NA, ncol = 7, nrow = length(comorbs)))

  colnames(out) <- c("var", "hrci", "p", "loghr", "lci", "uci", "prop")

  for (i in seq_along(comorbs)) {
    fit <- survfit(formula(paste0("Surv(", outtime, ",", outvar, "=='", outval, "') ~ ", comorbs[i])),
      data = data
    )

    sfit <- summary(fit, times = c(365))

    out[i, 7] <- paste0(rev(paste0(
      fn(100 - sfit$surv * 100, dig = 0), " (",
      fn(100 - sfit$upper * 100, dig = 0), "-",
      fn(100 - sfit$lower * 100, dig = 0), ")"
    )), collapse = "/")


    out[i, 1] <- comorbs[i]

    mod <- coxme::coxme(formula(paste0(
      "Surv(", outtime, ",", outvar, "=='", outval, "') ~ ", comorbs[i], " + ",
      paste0(modvarsns, collapse = "+"),
      " + (1 | num_nation)"
    )),
    data = data
    )

    se <- sqrt(diag(vcov(mod)))

    out[i, 2] <-
      paste0(
        fn(exp(mod$coefficients[1]), 1),
        " (",
        fn(exp(mod$coefficients[1] - global_z05 * se[1]), 1),
        "-",
        fn(exp(mod$coefficients[1] + global_z05 * se[1]), 1),
        ")"
      )
    out[i, 3] <- fn((1 - pnorm(abs(mod$coeff[1] / se[1]))) * 2, dig = 3, p = TRUE)

    out[i, 4] <- mod$coefficients[1]

    out[i, 5] <- mod$coefficients[1] - global_z05 * se[1]

    out[i, 6] <- mod$coefficients[1] + global_z05 * se[1]
  }

  # fix names
  forestdata <- out %>%
    mutate(Variable = case_when(
      var == "num_dmDiab_c1" ~ "Diabetes",
      var == "num_dmCopd" ~ "COPD",
      var == "num_dmHyChol" ~ "Kidney dysfunction",
      var == "num_dmHepa" ~ "Hepatic dysfunction",
      var == "num_dmDis" ~ "Current malignancy",
      var == "num_dmApn" ~ "Sleep apnea",
      var == "num_dmPark" ~ "Parkinson",
      var == "num_dmDepr" ~ "Depression",
      var == "num_dmStroke" ~ "Stroke/TIA",
      var == "num_dmPvd" ~ "PVD",
      var == "num_dmRheu" ~ "Rheumatoid arthritis",
      var == "anemia" ~ "Anemia"
    ), 
    c = 1:n()) 

  cextext <- 1

  minmy <- min(round(exp(min(forestdata$lci, na.rm = T)), 1), 1)
  maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

  # c(bottom, left, top, right)
  par(mar = c(4, 25, 0.5, 0.5) + 0.2)

 gplots::plotCI(
    x = forestdata$loghr, y = forestdata$c,
    li = forestdata$lci,
    ui = forestdata$uci,
    err = "x",
    cex = 1.5,
    xlim = c(
      log(minmy),
      log(maxmy)
    ),
    xlab = "HR (95% CI)",
    ylim = c(1, nrow(forestdata) + 1),
    axes = FALSE,
    ylab = "",
    main = NA,
    pch = 22,
    pt.bg = global_cols[2],
    col = global_cols[2],
    lwd = 2,
    cex.lab = cextext, 
    gap = 0
  )

  matplot(c(log(1), log(1)), c(-1, nrow(forestdata) + 0.5), type = "l", lwd = 2, lty = 3, add = TRUE, col = 1)

  axismy <- seq(minmy, maxmy, 0.1)
  axismy2 <- axismy
  axismy2[!axismy %in% c(minmy, maxmy)] <- NA

  axis(1,
    cex.axis = cextext, at = log(axismy),
    labels = axismy2
  )
  axis(1,
    cex.axis = cextext, at = log(1),
    labels = 1
  )

  axis(2,
    at = nrow(forestdata) + 1,
    labels = "Comorbidity",
    cex.axis = cextext, tick = FALSE, las = 2, line = 24, hadj = 0, font = 2
  )
  axis(2,
    at = nrow(forestdata) + 1,
    labels = "% Event (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 12, hadj = 0.5, font = 2
  )
  axis(2,
    at = nrow(forestdata) + 1,
    labels = "HR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 4.7, hadj = 0.5, font = 2
  )
  axis(2,
    at = nrow(forestdata) + 1,
    labels = "P-value",
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5, font = 2
  )

  axis(2,
    at = forestdata$c,
    labels = forestdata$Variable,
    cex.axis = cextext, tick = FALSE, las = 2, line = 24, hadj = 0
  )
  axis(2,
    at = forestdata$c,
    labels = forestdata$prop,
    cex.axis = cextext, tick = FALSE, las = 2, line = 12, hadj = 0.5
  )
  axis(2,
    at = forestdata$c,
    labels = forestdata$hrci,
    cex.axis = cextext, tick = FALSE, las = 2, line = 4.7, hadj = 0.5
  )
  axis(2,
    at = forestdata$c,
    labels = forestdata$p,
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5
  )
}
```

```{r indforestmort, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause mortality"}
indforest(
  data = edata %>% filter(survpop), outvar = "out_death", outtime = "outtime_death"
)
```

```{r indforestmortref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause mortality - rEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "<41%"), outvar = "out_death", outtime = "outtime_death"
)
```

```{r indforestmortmref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause mortality - mrEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"), outvar = "out_death", outtime = "outtime_death"
)
```

```{r indforestmortpef, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause mortality - pEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"), outvar = "out_death", outtime = "outtime_death"
)
```

```{r indforesthosp, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause hospitalization"}
indforest(
  data = edata %>% filter(survpop), outvar = "out_hosp", outtime = "outtime_hosp"
)
```

```{r indforesthospref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause hospitalization - rEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "<41%"), outvar = "out_hosp", outtime = "outtime_hosp"
)
```

```{r indforesthospmref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause hospitalization - mrEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"), outvar = "out_hosp", outtime = "outtime_hosp"
)
```

```{r indforesthosppef, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause hospitalization - pEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"), outvar = "out_hosp", outtime = "outtime_hosp"
)
```

```{r indforestcvmort, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and CV mortality"}
indforest(
  data = edata %>% filter(survpop), outvar = "out_deathcv", outtime = "outtime_death"
)
```

```{r indforestcvmortref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and CV mortality - rEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "<41%"), outvar = "out_deathcv", outtime = "outtime_death"
)
```

```{r indforestcvmortmref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and CV mortality - mrEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"), outvar = "out_deathcv", outtime = "outtime_death"
)
```

```{r indforestcvmortpef, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and CV mortality - pEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"), outvar = "out_deathcv", outtime = "outtime_death"
)
```

```{r indforesthosphf, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization"}
indforest(
  data = edata %>% filter(survpop), outvar = "out_hosphf", outtime = "outtime_hosphf"
)
```

```{r indforesthoshfpref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization - rEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "<41%"), outvar = "out_hosphf", outtime = "outtime_hosphf"
)
```

```{r indforesthosphfmref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization - mrEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"), outvar = "out_hosphf", outtime = "outtime_hosphf"
)
```

```{r indforesthosphfpef, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization - pEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"), outvar = "out_hosphf", outtime = "outtime_hosphf"
)
```

```{r indforestdeathhosphf, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and all-cause mortality/HF hospitalization"}
indforest(
  data = edata %>% filter(survpop), outvar = "out_deathhosphf", outtime = "outtime_hosphf"
)
```

```{r indforestdeathhoshfpref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization - rEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "<41%"), outvar = "out_deathhosphf", outtime = "outtime_hosphf"
)
```

```{r indforestdeathhosphfmref, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization - mrEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"), outvar = "out_deathhosphf", outtime = "outtime_hosphf"
)
```

```{r indforestdeathhosphfpef, cache=cacheon, dependson="indforestfunc", fig.cap="Association between individual non-cardiac comorbidities and HF hospitalization - pEF"}
indforest(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"), outvar = "out_deathhosphf", outtime = "outtime_hosphf"
)
```
