
```{r outforestefab, cache=cacheon}

tabforest <- function(data, outtime, outvar, outval = 1) {
  levs <- levels(edata$nocom_cat)
  levsef <- levels(edata$num_Ef_cat)
  
  out <- data.frame(matrix(NA, ncol = 8, nrow = length(levs) * 3))
  
  out[, 2] <- rep(paste0(levs,"C"), 3)
  
  colnames(out) <- c("EF", "No comorbs", "prop", "hrci", "p", "loghr", "lci", "uci")
  out[, 1] <- rep(levsef, each = length(levs))
  
  fit <- survfit(formula(paste0("Surv(", outtime, ",", outvar, "=='", outval, "') ~ num_Ef_cat + nocom_cat")),
                 data = data
  )
  
  sfit <- summary(fit, times = c(365))
  
  out[, 3] <- paste0(
    fn(100 - sfit$surv * 100, dig = 0), " (",
    fn(100 - sfit$upper * 100, dig = 0), "-",
    fn(100 - sfit$lower * 100, dig = 0), ")"
  )
  
  for (i in seq_along(levsef)) {
    #out[i + ((i - 1) * (length(levs) - 1)), 1] <- levsef[i]
    
    mod <- coxme::coxme(formula(paste0(
      "Surv(", outtime, ",", outvar, " == '", outval, "') ~ nocom_cat * relevel(num_Ef_cat, ref = '", levsef[i], "') + ",
      paste0(modvarsns, collapse = "+"), " + (1 | num_nation)"
    )),
    data = data
    )
    
    se <- sqrt(diag(vcov(mod)))
    
    rownos <- 1:4
    colplace <- (i + ((i - 1) * (length(levs) - 1))):(i * length(levs))
    out[colplace, 4] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos]), 1),
        " (",
        fn(exp(mod$coefficients[rownos] - global_z05 * se[rownos]), 1),
        "-",
        fn(exp(mod$coefficients[rownos] + global_z05 * se[rownos]), 1),
        ")"
      )
    )
    out[colplace, 5] <- c(NA, fn((1 - pnorm(abs(mod$coeff[rownos] / se[rownos]))) * 2, dig = 3, p = TRUE))
    
    out[colplace, 6] <- c(NA, mod$coefficients[rownos])
    
    out[colplace, 7] <- c(NA, mod$coefficients[rownos] - global_z05 * se[rownos])
    
    out[colplace, 8] <- c(NA, mod$coefficients[rownos] + global_z05 * se[rownos])
  }
  return(out)
}

deathforest <- tabforest(
  data = edata %>% filter(survpop), outvar = "out_death", outtime = "outtime_death"
)

plotforest <- function(forestdata) {
  forestdata <- forestdata %>%
    mutate(c = 1:n()) %>%
    arrange(desc(c))
  
  nf <- nrow(forestdata)
  
  cextext <- 1
  
  minmy <- round(exp(min(forestdata$lci, na.rm = T)), 1)
  maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)
  
  # c(bottom, left, top, right)
  par(mar = c(4, 16, 0, 0) + 0.2)
  
  plot(forestdata$loghr, 1:nf,
       cex = 1.5,
       xlim = c(
         log(minmy),
         log(maxmy)
       ),
       xlab = "HR (95% CI)",
       ylim = c(1, nf + 1),
       axes = FALSE,
       ylab = NA,
       main = NA,
       type = "p",
       pch = 22,
       bg = global_kicols[1],
       col = global_kicols[1]
  )
  
  for (i in 1:nf) {
    if (!is.na(forestdata$lci[i])) {
      matplot(c(forestdata$lci[i], forestdata$uci[i]), c(i, i),
              type = "l", add = TRUE, col = global_kicols[1], cex = 1
      )
    }
  }
  
  matplot(c(log(1), log(1)), c(-1, nf), type = "l", lwd = 1, lty = 3, add = TRUE, col = 1)
  
  axismy <- seq(minmy, maxmy, 0.1)
  axismy2 <- axismy
  axismy2[!axismy %in% c(minmy, maxmy)] <- NA
  
  axis(1,
       cex.axis = cextext, at = log(axismy),
       labels = axismy2
  )
  axis(1,
       cex.axis = cextext, at = log(1),
       labels = 1
  )
  
  axis(2,
       at = 1:nf,
       labels = forestdata$`No comorbs`,
       cex.axis = cextext, tick = FALSE, las = 2, line = 15, hadj = 0, font = 2
  )
  axis(2,
       at = 1:nf,
       labels = forestdata$prop,
       cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0.5
  )
  axis(2,
       at = 1:nf,
       labels = forestdata$hrci,
       cex.axis = cextext, tick = FALSE, las = 2, line = 5, hadj = 0.5
  )
  axis(2,
       at = 1:nf,
       labels = forestdata$p,
       cex.axis = cextext, tick = FALSE, las = 1, line = .5, hadj = 0.5
  )
  
  #axis(2,
  #     at = nf + 1,
  #     labels = "No comorbs",
  #     cex.axis = cextext, tick = FALSE, las = 2, line = 14, hadj = 0, font = 2
  #)
  axis(2,
       at = nf + 1,
       labels = "% Death 1yr\n(95% CI)",
       cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0.5, font = 2
  )
  axis(2,
       at = nf + 1,
       labels = "HR\n(95% CI)",
       cex.axis = cextext, tick = FALSE, las = 2, line = 5, hadj = 0.5, font = 2
  )
  axis(2,
       at = nf + 1,
       labels = "P-value",
       cex.axis = cextext, tick = FALSE, las = 2, line = .5, hadj = 0.5, font = 2
  )
  
  #text(x = log(maxmy) + log(maxmy) * 0.15, y = nf / 2, labels = paste0("P-value interaction: ", last(forestdata$pint)), srt = -90)
}
```

```{r outforestdeathabref, cache=cacheon, dependson=c("outforestefab"), fig.cap="Association between no of non-cardiac comorbidities and all-cause mortality - rEF"}
plotforest(deathforest %>% filter(EF == "<41%"))
```

```{r outforestdeathabmref, cache=cacheon, dependson=c("outforestefab"), fig.cap="Association between no of non-cardiac comorbidities and all-cause mortality - mrEF"}
plotforest(deathforest %>% filter(EF == "41-49%"))
```

```{r outforestdeathabpef, cache=cacheon, dependson=c("outforestefab"), fig.cap="Association between no of non-cardiac comorbidities and all-cause mortality - pEF"}
plotforest(deathforest %>% filter(EF == ">=50%"))
```