```{r outtabfunc, cache=cacheon}

outfunc <- function(data, outvarname, outvar, outval = NULL, outtime = NULL, outvarcomp = NULL, model) {
  if (!is.null(outvarcomp)) {
    nr <- 4
  } else {
    if (model == "ord") {
      nr <- 2 + length(levels(data %>% pull(!!sym(outvar))))
    }
    else {
      nr <- 3
    }
  }
  out <- data.frame(matrix(NA, ncol = 7, nrow = nr))

  out[1, 1] <- outvarname

  colnames(out) <- c(
    "Outcome", "Model", levels(edata$nocom_cat)
  )

  if (model == "bin") {

    # n (%)
    out[1, 2] <- "n (%)"

    np <- data %>%
      filter(!is.na(!!sym(outvar))) %>%
      group_by(nocom_cat) %>%
      count(!!sym(outvar)) %>%
      mutate(
        p = fn(n / sum(n) * 100, 1),
        np = paste0(n, " (", p, "%)")
      ) %>%
      filter(!!sym(outvar) == outval)

    out[1, 3:7] <- np$np

    # crude
    mod <- summary(lme4::glmer(formula(paste0(outvar, " == '", outval, "' ~ nocom_cat + (1 | num_nation)")),
      family = "binomial",
      data = data
    ))

    rownos <- str_detect(rownames(mod$coefficients), "nocom_cat")

    out[2, 2] <- "Crude OR (95% CI), p-value"
    out[2, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos, 1]), 1),
        " (",
        fn(exp(mod$coefficients[rownos, 1] - global_z05 * mod$coefficients[rownos, 2]), 1),
        "-",
        fn(exp(mod$coefficients[rownos, 1] + global_z05 * mod$coefficients[rownos, 2]), 1),
        "), ",
        fn(mod$coefficients[rownos, 4], dig = 3, p = T)
      )
    )

    # adj

    mod <- summary(lme4::glmer(formula(paste0(outvar, " == '", outval, "' ~ nocom_cat + (1 | num_nation) + ", paste0(modvars, collapse = "+"))),
      family = "binomial",
      data = data
    ))

    rownos <- str_detect(rownames(mod$coefficients), "nocom_cat")

    out[3, 2] <- "Adjusted OR (95% CI), p-value"
    out[3, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos, 1]), 1),
        " (",
        fn(exp(mod$coefficients[rownos, 1] - global_z05 * mod$coefficients[rownos, 2]), 1),
        "-",
        fn(exp(mod$coefficients[rownos, 1] + global_z05 * mod$coefficients[rownos, 2]), 1),
        "), ",
        fn(mod$coefficients[rownos, 4], dig = 3, p = T)
      )
    )
  }

  if (model == "negbin") {

    # med (q1-q3)
    out[1, 2] <- "Median (q1-q3)"

    med <- data %>%
      filter(!is.na(!!sym(outvar))) %>%
      group_by(nocom_cat) %>%
      summarise(
        med = fn(median(!!sym(outvar)), dig = 1),
        q1 = fn(quantile(!!sym(outvar), p = 0.25), dig = 1),
        q3 = fn(quantile(!!sym(outvar), p = 0.75), dig = 1)
      ) %>%
      mutate(out = paste0(med, " (", q1, "-", q3, ")"))

    out[1, 3:7] <- med$out

    # crude
    mod <- summary(lme4::glmer.nb(formula(paste0(outvar, " ~ nocom_cat + (1 | num_nation)")),
      data = data
    ))

    rownos <- str_detect(rownames(mod$coefficients), "nocom_cat")

    out[2, 2] <- "Crude IRR (95% CI), p-value"
    out[2, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos, "Estimate"]), 1),
        " (",
        fn(exp(mod$coefficients[rownos, "Estimate"] - global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "-",
        fn(exp(mod$coefficients[rownos, "Estimate"] + global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "), ",
        fn(mod$coefficients[rownos, "Pr(>|z|)"], dig = 3, p = T)
      )
    )

    # adj

    mod <- summary(lme4::glmer.nb(formula(paste0(outvar, " ~ nocom_cat + (1 | num_nation) + ", paste0(modvars, collapse = "+"))),
      data = data
    ))

    rownos <- str_detect(rownames(mod$coefficients), "nocom_cat")

    out[3, 2] <- "Adjusted IRR (95% CI), p-value"
    out[3, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos, "Estimate"]), 1),
        " (",
        fn(exp(mod$coefficients[rownos, "Estimate"] - global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "-",
        fn(exp(mod$coefficients[rownos, "Estimate"] + global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "), ",
        fn(mod$coefficients[rownos, "Pr(>|z|)"], dig = 3, p = T)
      )
    )
  }

  if (model == "ord") {

    # n (%)
    out[1:(nr - 2), 2] <- paste0("n (%) ", levels(data %>% pull(!!sym(outvar))))

    np <- data %>%
      filter(!is.na(!!sym(outvar))) %>%
      group_by(nocom_cat) %>%
      count(!!sym(outvar)) %>%
      mutate(
        p = fn(n / sum(n) * 100, 1),
        np = paste0(n, " (", p, "%)")
      )

    out[1:(nr - 2), 3:7] <- np$np


    # crude
    mod <- summary(ordinal::clmm(formula(paste0(outvar, " ~ nocom_cat + (1 | num_nation)")),
      data = data
    ))

    rownos <- str_detect(rownames(mod$coefficients), "nocom_cat")
    out[nr - 1, 2] <- "Crude OR (95% CI), p-value"
    out[nr - 1, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos, "Estimate"]), 1),
        " (",
        fn(exp(mod$coefficients[rownos, "Estimate"] - global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "-",
        fn(exp(mod$coefficients[rownos, "Estimate"] + global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "), ",
        fn(mod$coefficients[rownos, "Pr(>|z|)"], dig = 3, p = T)
      )
    )

    # adj
    mod <- summary(ordinal::clmm(formula(paste0(outvar, " ~ nocom_cat + (1 | num_nation) + ", paste0(modvars, collapse = " + "))),
      data = data
    ))

    rownos <- str_detect(rownames(mod$coefficients), "nocom_cat")
    out[nr, 2] <- "Adjusted OR (95% CI), p-value"
    out[nr, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos, "Estimate"]), 1),
        " (",
        fn(exp(mod$coefficients[rownos, "Estimate"] - global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "-",
        fn(exp(mod$coefficients[rownos, "Estimate"] + global_z05 * mod$coefficients[rownos, "Std. Error"]), 1),
        "), ",
        fn(mod$coefficients[rownos, "Pr(>|z|)"], dig = 3, p = T)
      )
    )
  }

  if (model == "cox") {

    ## incidence rate
    out[1, 2] <- "No events, sum py, incidence rate/1000py (95% CI)"

    ev <- data %>%
      group_by(nocom_cat) %>%
      summarise(
        ev = sum(!!sym(outvar) == outval),
        .groups = "rowwise"
      )

    s <- data %>%
      group_by(nocom_cat) %>%
      summarise(
        s = sum(!!sym(outtime) / 365.25),
        .groups = "rowwise"
      )
    r <- pois.exact(x = ev$ev, pt = s$s / 1000)

    out[1, 3:7] <- paste0(
      ev$ev, ", ",
      fn(s$s, dig = 0), ", ",
      fn(r$rate, dig = 0), " (",
      fn(r$lower, dig = 0), "-",
      fn(r$upper, dig = 0), ")"
    )


    out[2, 2] <- "Crude HR (95% CI), p-value"

    # crude
    mod <- coxme::coxme(formula(paste0("Surv(", outtime, ",", outvar, " == '", outval, "') ~ nocom_cat + (1 | num_nation)")),
      data = data
    )
    se <- sqrt(diag(vcov(mod)))

    rownos <- str_detect(names(mod$coefficients), "nocom_cat")

    out[2, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos]), 1),
        " (",
        fn(exp(mod$coefficients[rownos] - global_z05 * se[rownos]), 1),
        "-",
        fn(exp(mod$coefficients[rownos] + global_z05 * se[rownos]), 1),
        "), ",
        fn((1 - pnorm(abs(mod$coeff[rownos] / se[rownos]))) * 2, dig = 3, p = TRUE)
      )
    )

    # adj
    out[3, 2] <- "Adjusted HR (95% CI), p-value"

    mod <- coxme::coxme(formula(paste0(
      "Surv(", outtime, ",", outvar, " == '", outval, "') ~ nocom_cat  + ",
      paste0(modvars, collapse = "+"), " + (1 | num_nation)"
    )),
    data = data
    )
    se <- sqrt(diag(vcov(mod)))

    rownos <- str_detect(names(mod$coefficients), "nocom_cat")

    out[3, 3:7] <- c(
      "ref",
      paste0(
        fn(exp(mod$coefficients[rownos]), 1),
        " (",
        fn(exp(mod$coefficients[rownos] - global_z05 * se[rownos]), 1),
        "-",
        fn(exp(mod$coefficients[rownos] + global_z05 * se[rownos]), 1),
        "), ",
        fn((1 - pnorm(abs(mod$coeff[rownos] / se[rownos]))) * 2, dig = 3, p = TRUE)
      )
    )

    if (!is.null(outvarcomp)) {
      out[4, 2] <- "Adjusted HR (95% CI), p-value, death as competing risk"

      modvarskont <- modvars[sapply(edata %>% select(!!!syms(modvars)), class) != "factor"]
      nams <- names(edata)
      modvarscr <- c(nams[str_detect(nams, "_cr_")], modvarskont)

      mod <- summary(crr(data %>% pull(!!sym(outtime)),
        data %>% pull(!!sym(outvarcomp)),
        data %>% select(all_of(modvarscr)),
        failcode = 1, cencode = 0
      ))

      rownos <- str_detect(rownames(mod$conf.int), "nocom_cat")

      out[4, 3:7] <- c(
        "ref",
        paste0(
          fn(mod$conf.int[rownos, "exp(coef)"], 1),
          " (",
          fn(mod$conf.int[rownos, "2.5%"], 1),
          "-",
          fn(mod$conf.int[rownos, "97.5%"], 1),
          "), ",
          fn(mod$coef[rownos, "p-value"], dig = 3, p = TRUE)
        )
      )
    }
  }
  return(out)
}
```

```{r outtab, include=FALSE, dependson="outtabfunc", cache=cacheon}
admissionnyha <- outfunc(data = edata, outvarname = "NYHA at admission", outvar = "num_hsNyha", outval = NULL, outtime = NULL, model = "ord")
dischargenyha <- outfunc(data = edata, outvarname = "NYHA at discharge", outvar = "num_dcNyha", outval = NULL, outtime = NULL, model = "ord")
decreasenyha <- outfunc(data = edata, outvarname = "Decrease in NYHA", outvar = "decrease_Nyha", outval = "Yes", outtime = NULL, model = "bin")
los <- outfunc(data = edata, outvarname = "Lenght of stay", outvar = "num_delayhosp", outval = NULL, outtime = NULL, model = "negbin")
inhospmort <- outfunc(data = edata, outvarname = "In-hospital mortality", outvar = "out_death_inhosp", outval = "Yes", outtime = NULL, model = "bin")
death <- outfunc(
  data = edata %>% filter(survpop), outvarname = "All-cause mortality", outvar = "out_death", outval = 1,
  outtime = "outtime_death", model = "cox"
)
hosp <- outfunc(
  data = edata %>% filter(survpop), outvarname = "All-cause hosp", outvar = "out_hosp",
  outval = 1, outtime = "outtime_hosp", model = "cox", outvarcomp = "out_hosp_cr"
)
cvdeath <- outfunc(
  data = edata %>% filter(survpop), outvarname = "CV mortality", outvar = "out_deathcv",
  outval = 1, outtime = "outtime_death", model = "cox", outvarcomp = "out_deathcv_cr"
)
hfhosp <- outfunc(
  data = edata %>% filter(survpop), outvarname = "HF hosp", outvar = "out_hosphf",
  outval = 1, outtime = "outtime_hosphf", model = "cox", outvarcomp = "out_hosphf_cr"
)
deathhfhosp <- outfunc(
  data = edata %>% filter(survpop), outvarname = "All-cause mortality/HF hosp", outvar = "out_deathhosphf",
  outval = 1, outtime = "outtime_hosphf", model = "cox"
)

outall <- bind_rows(
  admissionnyha,
  dischargenyha,
  decreasenyha,
  los,
  inhospmort,
  death,
  hosp,
  cvdeath,
  hfhosp,
  deathhfhosp
)
```

```{r outtabprint, dependson=c("outtabfunc", "outtab"), cache=cacheon}
write.xlsx(outall, paste0("./output/tabs/outall", Sys.Date(), ".xlsx"), rowNames = FALSE)

default_kable(outall,
  caption = sanitize_text("Associations between NYHA/outcomes and no of non-cardiac comorbidities")
)
```
