```{r uniforestmorttab, cache=cacheon}
tabforestuni <- function(data, outtime, outvar, outval = 1) {
  out <- data.frame(matrix(NA, ncol = 7, nrow = length(comorbs)))

  colnames(out) <- c("var", "hrci", "p", "loghr", "lci", "uci", "prop")

  for (i in seq_along(comorbs)) {
    fit <- survfit(formula(paste0("Surv(", outtime, ",", outvar, "=='", outval, "') ~ ", comorbs[i])),
      data = data
    )

    sfit <- summary(fit, times = c(365))

    out[i, 7] <- paste0(rev(paste0(
      fn(100 - sfit$surv * 100, dig = 0), " (",
      fn(100 - sfit$upper * 100, dig = 0), "-",
      fn(100 - sfit$lower * 100, dig = 0), ")"
    )), collapse = "/")


    out[i, 1] <- comorbs[i]

    mod <- coxme::coxme(formula(paste0(
      "Surv(", outtime, ",", outvar, "=='", outval, "') ~ ", comorbs[i], " + (1 | num_nation)"
    )),
    data = data
    )

    se <- sqrt(diag(vcov(mod)))

    out[i, 2] <-
      paste0(
        fn(exp(mod$coefficients[1]), 1),
        " (",
        fn(exp(mod$coefficients[1] - global_z05 * se[1]), 1),
        "-",
        fn(exp(mod$coefficients[1] + global_z05 * se[1]), 1),
        ")"
      )
    out[i, 3] <- fn((1 - pnorm(abs(mod$coeff[1] / se[1]))) * 2, dig = 3, p = TRUE)

    out[i, 4] <- mod$coefficients[1]

    out[i, 5] <- mod$coefficients[1] - global_z05 * se[1]

    out[i, 6] <- mod$coefficients[1] + global_z05 * se[1]
  }
  return(out)
}
```

```{r uniforestmortplot, cache=cacheon, dependson="uniforestmorttab"}
plotforest <- function(forestdata, minmy = NULL, maxmy = NULL) {

  # fix names
  forestdata <- forestdata %>%
    mutate(Variable = case_when(
      var == "num_dmDiab_c1" ~ "Diabetes",
      var == "num_dmCopd" ~ "COPD",
      var == "num_dmHyChol" ~ "Kidney dysfunction",
      var == "num_dmHepa" ~ "Hepatic dysfunction",
      var == "num_dmDis" ~ "Current malignancy",
      var == "num_dmApn" ~ "Sleep apnea",
      var == "num_dmPark" ~ "Parkinson",
      var == "num_dmDepr" ~ "Depression",
      var == "num_dmStroke" ~ "Stroke/TIA",
      var == "num_dmPvd" ~ "PVD",
      var == "num_dmRheu" ~ "Rheumatoid arthritis",
      var == "anemia" ~ "Anemia"
    )) %>%
    arrange(loghr)

  cextext <- 1

  if (is.null(minmy)) minmy <- round(exp(min(forestdata$lci, na.rm = T)), 1)
  if (is.null(maxmy)) maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

  # c(bottom, left, top, right)
  par(mar = c(4, 25, 1, 0.5) + 0.2)


  plot(forestdata$loghr, 1:nrow(forestdata),
    cex = 1.5,
    xlim = c(
      log(minmy),
      log(maxmy)
    ),
    xlab = "HR (95% CI)",
    ylim = c(1, nrow(forestdata) + 1),
    axes = FALSE,
    ylab = NA,
    main = NA,
    type = "p",
    pch = 22,
    bg = global_kicols[1],
    col = global_kicols[1]
  )

  for (i in 1:nrow(forestdata)) {
    if (!is.na(forestdata$lci)[i]) {
      matplot(c(forestdata$lci[i], forestdata$uci[i]), c(i, i),
        type = "l", add = TRUE, col = global_kicols[1], cex = 1
      )
    }
  }

  matplot(c(log(1), log(1)), c(-1, nrow(forestdata)), type = "l", lwd = 1, lty = 3, add = TRUE, col = 1)

  axismy <- seq(minmy, maxmy, 0.1)
  axismy2 <- axismy
  axismy2[!axismy %in% c(minmy, maxmy)] <- NA

  axis(1,
    cex.axis = cextext, at = log(axismy),
    labels = axismy2
  )
  axis(1,
    cex.axis = cextext, at = log(1),
    labels = 1
  )

  axis(2,
    at = nrow(forestdata) + 1,
    labels = "Comorbidity",
    cex.axis = cextext, tick = FALSE, las = 2, line = 24, hadj = 0, font = 2
  )
  axis(2,
    at = nrow(forestdata) + 1,
    labels = "% Outcome 1yr (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 12, hadj = 0.5, font = 2
  )
  axis(2,
    at = nrow(forestdata) + 1,
    labels = "HR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 4.7, hadj = 0.5, font = 2
  )
  axis(2,
    at = nrow(forestdata) + 1,
    labels = "P-value",
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5, font = 2
  )

  axis(2,
    at = 1:nrow(forestdata),
    labels = forestdata$Variable,
    cex.axis = cextext, tick = FALSE, las = 2, line = 24, hadj = 0
  )
  axis(2,
    at = 1:nrow(forestdata),
    labels = forestdata$prop,
    cex.axis = cextext, tick = FALSE, las = 2, line = 12, hadj = 0.5
  )
  axis(2,
    at = 1:nrow(forestdata),
    labels = forestdata$hrci,
    cex.axis = cextext, tick = FALSE, las = 2, line = 4.7, hadj = 0.5
  )
  axis(2,
    at = 1:nrow(forestdata),
    labels = forestdata$p,
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5
  )
}
```

```{r uniforestmortref, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and all-cause mortality - rEF"}
ref <- tabforestuni(
  data = edata %>% filter(survpop & num_Ef_cat == "<41%"), outvar = "out_death", outtime = "outtime_death")
plotforest(forestdata = ref)
```

```{r uniforestmortmref, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and all-cause mortality - mrEF"}
mref <- tabforestuni(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"), outvar = "out_death", outtime = "outtime_death")
plotforest(forestdata = mref)
```

```{r uniforestmortpef, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and all-cause mortality - pEF"}
pef <- tabforestuni(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"), outvar = "out_death", outtime = "outtime_death")
plotforest(forestdata = pef)
```

```{r uniforestmort, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and all-cause mortality"}
mort <- tabforestuni(
  data = edata %>% filter(survpop), outvar = "out_death", outtime = "outtime_death")
plotforest(forestdata = mort)
```

```{r uniforesthosp, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and all-cause hospitalization"}
hosp <- tabforestuni(
  data = edata %>% filter(survpop), outvar = "out_hosp", outtime = "outtime_hosp")
plotforest(forestdata = hosp)
```

```{r uniforestcvmort, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and CV mortality"}
cvmort <- tabforestuni(
  data = edata %>% filter(survpop), outvar = "out_deathcv", outtime = "outtime_death")
plotforest(forestdata = cvmort)
```

```{r uniforesthosphf, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and HF hospitalization"}
hosphf <- tabforestuni(
  data = edata %>% filter(survpop), outvar = "out_hosphf", outtime = "outtime_hosphf")
plotforest(forestdata = hosphf)
```

```{r uniforestdeathhosphf, cache=cacheon, dependson=c("uniforestmorttab", "uniforestmortplot"), fig.cap="Association between non-cardiac comorbidities and all-cause mortality/HF hospitalization"}
deathhosphf <- tabforestuni(
  data = edata %>% filter(survpop), outvar = "out_deathhosphf", outtime = "outtime_hosphf")
plotforest(forestdata = deathhosphf)
```
